### ISSUE TITLE
Problem withRUN groupadd -g 100 ssm

### ISSUE THREAD

**Issue by toutoumeteo** [neishm/rmnlib-install-docker#2]
Hi Mike,

This is André Plante working at Dorval with K. Uno and Michel Valin. 

I created a docker image from the Dockerfile of this repository on my Synology NAS. The only thing I has to modify was the number in the groupadd command. The number 100 was already taken and it was making the image creation to abort. I test interactively and found that number 500 was OK. I am not too familiar with user groupe. Is this a change that could/should be made in your repository?

RUN groupadd -g 500 ssm

Thanks for the good work.

André

**Comment by toutoumeteo** [comment]
Mike,

I have a similar error on my MacBook Pro MacOS Mojave

Step 5/13 : RUN groupadd -g 20 ssm
 ---> Running in 9d1904e9630d
groupadd: GID '20' already exists
The command '/bin/sh -c groupadd -g 20 ssm' returned a non-zero code: 4
make: *** [defaut] Error 4

**Comment by toutoumeteo** [comment]
Mike,

Yes, it solves the issue on both my Mac and my NAS. Thanks for the fix.

Would You know how to acquire the fortran compiler environment. The goal for me in using rmnlib-install is to continue the development of vgrid after I retire next April. So I would like to be able to compile the vgrid code in the docker image on my Mac.

Many thanks

André

**Comment by jeixav** [comment]
Salut @toutoumeteo, 

By Fortran compiler environment, I think you mean s.f90 and s.compile. Did you try?
```bash
. $HOME/.profile_armnlib
```
This comes from rmnlib-install's README:
https://github.com/mfvalin/rmnlib-install/blob/1e5a2771d6bb7d4f3f3cf66a501beb847696ec60/README.md#L35

Kristjan

**Comment by toutoumeteo** [comment]
I solved my problem by adding the following RUN commands in the Dockerfile.template  The cloning of vgrid is there because I want to run the vgrid tests, they are not in Michel Valin rmnlib-install which is fine. With the remaining RUN commands I get a fully working compiling environment and my vgrid tests works.

RUN git clone https://gitlab.com/ECCC_CMDN/vgrid.git
RUN echo 'export COMP_ARCH=gfortran' >> .bashrc
RUN echo '. ./.profile_armnlib' >> .bashrc
RUN echo '. r.load.dot /home/ssm/ssm-domains-base/lib' >> .bashrc

André

**Comment by neishm** [comment]
Hi André,

I was able to get compilation working with the following two lines:
```
. $HOME/.profile_armnlib
. r.load.dot dev/gfortran
```
The second line was taken from the [latest commit](https://gitlab.com/ECCC_CMDN/vgrid/commit/04580761681c8f5abd32664d5b2e625d5039dde2) in your `vgrid` repository.  I omitted the `dev/base` package because it looks like Michel already includes it in the `dev/gfortran` shortcut?

Mike

**Comment by neishm** [comment]
Latest version now has those lines in `.bashrc`, so hopefully the compiler is ready to use out-of-the-box...

**Comment by toutoumeteo** [comment]
Thanks for the precision and addition.

Michel told me that he doesn't set the compiler env by default since it cannot be undone. But for a Docker image I think it is fine.

Note that .bashrc will not be dotted for none interactive session. Therefore if one wants to compile stuff in a continuous integration (CI) contexte with Docker, the .bashrc will not be dotted. Then the script executed by the CI process would have to set the complete armnlib env.

**Comment by neishm** [comment]
Closing this issue, since the original problem (conflicting group id) should be resolved now.
