### ISSUE TITLE
Test with 18.04

### ISSUE THREAD

**Issue by toutoumeteo** [neishm/rmnlib-install-docker#3]
Hi Mike,

I've tested with 18.04. The only thing that was missing was the rsync package. I just added it in the apt-get list in the Dockerfile.template and every ran fine. I don't know  how or if You can integrate this change in your master branch.

André

**Comment by neishm** [comment]
Thanks for adding 18.04 support, André!  The updates look good, I'm just going to add support for other versions (like 16.04) back into the Makefile, and add an alias `rmnlib-install` to point to `rmnlib-install-18.04`.  Or should the default `rmnlib-install` point to `rmnlib-install-16.04`?  The frontend machines are still running `14.04`, I don't know what their plans are for the next distro.

**Comment by neishm** [comment]
Okay, sounds good to me.
