### ISSUE TITLE
Hard-code user and group ids in the container?

### ISSUE THREAD

**Issue by neishm** [neishm/rmnlib-install-docker#6]
At the moment they're dynamically set to the host user's id at build time.  This was intended to make it easier to mount volumes via the `-v` option to `docker run`.  Does anyone actually use volumes with this docker image, though?  Hard-coding the ids to some predetermined value (like 999?) would make it easier to push the image to a central repository like docker hub, and avoids other potential pitfalls like what happened in #2.

**Comment by jeixav** [comment]
@neishm, I don't mount volumes with the rmnlib Docker image, so hard-coding the user id seems fine.

**Comment by neishm** [comment]
I just updated this in the master branch.  Mounting volumes should still (sort of) work, but the files will be owned by some non-existent user.
